### PR TITLE
Attempt to run 3dgeotop with point classifications in 3dtiles

### PR DESCRIPTION
**Pull request by kamielverhelst**
@MarcoDuiker is working on a PR for `py3dtiles` to also extract classification data from an xyz file and to convert that to 3DTiles. 
I need this in order to make 3DTiles pointclouds that can be filtered on class. 

I created this first attempt at implementing Marco's change in this tool. During the Docker image build, the `py3dtiles` library is taken directly from Marco's forked repository.

### CODE REVIEW

**Comment by kamielverhelst** [comment]
I haven't tested yet, but the output of `py3dtiles info` don't show any classification attribute...

```

Tile Header
-----------
Magic Value:  b'pnts'
Version:  1
Tile byte length:  19912
Feature table json byte length:  84
Feature table bin byte length:  18480

Feature Table Header
--------------------
{'POINTS_LENGTH': 1232, 'POSITION': {'byteOffset': 0}, 'RGB': {'byteOffset': 14784}}

First point
-----------
Position: [ 0.3076916  -0.24979316 25.49692   ]
Color: [221 192  31]
Normal: None
```

**Comment by MarcoDuiker** [comment]
Are you aware of this branch: https://github.com/ProvincieZeeland/3DToolbox/tree/MRpy3dtiles ?

It has everything you need to convert geotop, including classification data.

**Comment by kamielverhelst** [comment]
> Are you aware of this branch: https://github.com/ProvincieZeeland/3DToolbox/tree/MRpy3dtiles ?
> 
> It has everything you need to convert geotop, including classification data.

I hadn't seen that, but that's great! I will try it out

**Comment by kamielverhelst** [comment]
I ran the code in your branch @MarcoDuiker and it seems like the generated `.pnts` files do not contain a 'Classification' attribute, it seems.

I used Bert Temme's tool [b3dm.tools](https://github.com/bertt/b3dm.tooling/tree/master) to obtain the batch table of `r.pnts`, which seems to be empty..

```
Action: Info                                                                                                                                                              
b3dm file: 3dtiles/r.pnts                                                                                                                                                 
b3dm header version: 1                                                                                                                                                   
b3dm header magic: pnts                                                                                                                                                   
b3dm header bytelength: 76632                                                                                                                                             
b3dm header featuretablejson length: 84                                                                                                                                   b3dm header batchtablejson length: 0                                                                                                                                      Feature table json: '{"POINTS_LENGTH":5101,"POSITION":{"byteOffset":0},"RGB":{"byteOffset":61212}}       '                                                                Batch table json: ''                                                                                                                                                      
Validation check: no errors                                                                                                                                               
glTF schema exception                                                                                                                                                     
Unable to read beyond the end of the stream.Model generated by <> seems to be malformed; Please, check the file at https://github.khronos.org/glTF-Validator/ 
```

**Comment by kamielverhelst** [comment]
I think I have found the issue. 
The code in the MRpy3dtiles misses the `--classification` argument for py3dtiles, which is why it doesn't create a batch table. I've tested it (in my own PR) and it works. The points now have the 'Classification' attribute

**Comment by MarcoDuiker** [comment]
Ah, OK, thank you. I did test with the --classification attribute. It seems that I did forget to include it in the docker container.
I'll fix it.

**Comment by MarcoDuiker** [comment]
done

**Comment by MarcoDuiker** [comment]
I'll close the pull request as is does not seem necessary.

**Pull request closed without merging**
